# Generated by Django 4.1.1 on 2022-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('person_name', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
